---
# Define global variables
variables:
    APP_NAME: your_app_name
    IMAGE_TAG: $CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
    DOCKER_REGISTRY: registry.example.com # TODO: update value
    DOCKER_IMAGE: $DOCKER_REGISTRY/$APP_NAME:$IMAGE_TAG # TODO: update value
before_script:
    - unset AWS_ACCESS_KEY_ID
    - unset AWS_SECRET_ACCESS_KEY
    - cat /etc/*release
    - export ARTIFACTORY_REPO="wes-aac-docker-preprod"
    - if echo "$CI_COMMIT_REF_NAME" | grep -q "^release"; then export ARTIFACTORY_REPO="wes-aac-docker-prod"; fi
    - if [ $CI_COMMIT_REF_NAME = "main" ]; then export ARTIFACTORY_REPO="wes-aac-docker-prod"; fi

# Define stages
stages:
    - build
    - test
    - deploy

# Define jobs
build:
    stage: build
    script:
        - echo "Building $APP_NAME..."
    # Add your build commands here

test:
    stage: test
    script:
        - echo "Running tests..."
    # Add your test commands here

deploy:
    stage: deploy
    script:
        - echo "Deploying $APP_NAME..."
    # Add your deployment commands here
    only:
        - master # Specify the branch to deploy, e.g., master
