---
variables:
  # fetch the branch name of the
    SOURCE_GIT_BRANCH_NAME: $[replace(variables['Build.SourceBranch'], 'refs/heads/', '')]

trigger:
    branches:
        include:
            - main
    paths:
        exclude:
            - README.md

# only trigger the CI job on PR (pull request) to the master branch
pr:
    branches:
        include:
            - '*'

pool:
    vmImage: ubuntu-latest

steps:
    - script: echo 'Starting pipeline...'
      displayName: Starting Pipeline

    - task: NodeTool@0
      inputs:
          versionSpec: 14.x
          displayName: Install Node.js

    - script: npm install
      displayName: Install Dependencies

    - script: npm run build
      displayName: Build Application

    - script: npm test
      displayName: Run Tests
