---
variables:
  # fetch the branch name of the
    SOURCE_GIT_BRANCH_NAME: $[replace(variables['Build.SourceBranch'], 'refs/heads/', '')]

trigger:
    branches:
        include:
            - main # Replace with the branch you want to trigger the pipeline
    paths:
        exclude:
            - README.md

# only trigger the CI job on PR (pull request) to the master branch
# pr:
#     branches:
#         include:
#             - '*'

pool:
    vmImage: ubuntu-latest

steps:
    #---------------------------------------------------------------------------------
    # Shell script examples
    #---------------------------------------------------------------------------------
    - script: |
          python --version
      displayName: Check Python version

    - task: ShellScript@2
      inputs:
          scriptPath: path/to/your/script.sh # Replace with the path to your shell script
      displayName: Shell script example

    #---------------------------------------------------------------------------------
    # Debugging task
    #---------------------------------------------------------------------------------
    - task: Bash@3
      inputs:
          targetType: inline
          script: env | sort
      displayName: List all predefined AZ pipeline vars

    #---------------------------------------------------------------------------------
    # Python examples
    #---------------------------------------------------------------------------------
    - script: |
          python --version
      displayName: Check Python version

    - task: UsePythonVersion@0
      inputs:
          versionSpec: 3.x # Replace with the desired Python version
          addToPath: true

    - task: PythonScript@0
      inputs:
          scriptSource: filePath
          scriptPath: path/to/your/script.py # Replace with the path to your Python script
          pythonInterpreter: python # Replace with the desired Python interpreter

    #---------------------------------------------------------------------------------
    # Copy/push logs
    #---------------------------------------------------------------------------------
    - task: PublishPipelineArtifact@1
      inputs:
          targetPath: $(Build.ArtifactStagingDirectory)
          artifactName: output
          publishLocation: pipeline

    - task: PublishBuildArtifacts@1
      inputs:
          artifactName: output
          pathToPublish: $(Build.ArtifactStagingDirectory)
